# Generated by Django 4.2.10 on 2025-07-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado')], max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
