# Generated by Django 4.2.10 on 2025-07-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
