# Generated by Django 4.2.10 on 2025-07-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0002_alter_perro_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perros/'),
        ),
    ]
